apiVersion: v1
kind: ServiceAccount
metadata:
  name: historyserver
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: raycluster-reader
rules:
- apiGroups: ["ray.io"]
  resources: ["rayclusters"]
  verbs: ["list", "get"]
# Need to add permission to read secrets if useAuthTokenMode is enabled,
# as the auth token is stored in a secret.
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: historyserver
  namespace: default
subjects:
- kind: ServiceAccount
  name: historyserver
  namespace: default
roleRef:
  kind: ClusterRole
  name: raycluster-reader
