apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kuberay-operator
  namespace: ray-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kuberay-operator
subjects:
- kind: ServiceAccount
  name: kuberay-operator
  namespace: ray-system
