apiVersion: ray.io/v1alpha1
kind: RayCluster
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
    # An unique identifier for the head node and workers of this cluster.
  name: raycluster-heterogeneous
spec:
  rayVersion: '1.0.1'
  ######################headService#################################
  # head service, follows Kubernetes standard
  headService: 
    metadata:
      name: "my-svc" # will automatically change to <clustername>-<svcName> i.e. <raycluster-heterogeneous-my-svc>, to avoid potential conflict
    spec:
      selector:
        identifier: raycluster-heterogeneous-head # <clusterName>-<rayNodeType>
      ports:
        - protocol: TCP
          port: 80
          targetPort: 6379
  ######################headGroupSpecs#################################
  # head group template and specs, (perhaps 'group' is not needed in the name)
  headGroupSpec:
    # the pod replicas in this group typed head (assuming there could be more than 1 in the future)
    replicas: 1
    # logical group name, for this called head-group, also can be functional
    # pod type head or worker
    # rayNodeType: head # Not needed since it is under the headgroup
    # the following params are used to complete the ray start: ray start --head --block --redis-port=6379 ...
    rayStartParams:
      port: '6379'
      object-manager-port: '12345'
      node-manager-port: '12346'
      object-store-memory: '100000000'
      redis-password: 'LetMeInRay'
      dashboard-host: '0.0.0.0'
      num-cpus: '1' # can be auto-completed from the limits
      node-ip-address: $MY_POD_IP # auto-completed as the head pod IP
    #pod template
    template:
      metadata:
        labels:
          # custom labels. NOTE: do not define custom labels start with `raycluster.`, they may be used in controller.
          # Refer to https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
          rayCluster: raycluster-heterogeneous # will be injected if missing
          rayNodeType: head # will be injected if missing, must be head or wroker
          groupName: headgroup # will be injected if missing
        # annotations for pod
        annotations:
          key: value
      spec:
        initContainers: # to avoid worker crashing before head service is created
        containers:
        - name: ray-head
          image: rayproject/autoscaler
          # you can have any command and args here to run your code. 
          # the below command/args will be appended after the Ray start command and it args, and executed after Ray start.
          command: ["python"]
          args:
          - '/opt/code.py'
          env:
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          ports:
          - containerPort: 6379
          volumeMounts:
          - mountPath: /opt
            name: config
        volumes:
        # You set volumes at the Pod level, then mount them into containers inside that Pod
        - name: config
          configMap:
            # Provide the name of the ConfigMap you want to mount.
            name: ray-code
            # An array of keys from the ConfigMap to create as files
            items:
            - key: code.py
              path: code.py
  workerGroupsSpec:
  # the pod replicas in this group typed worker
  - replicas: 2
    minReplicas: 1
    maxReplicas: 10
    # logical group name, for this called small-group, also can be functional
    groupName: small-group
    # if worker pods need to be added, we can simply increment the replicas
    # if worker pods need to be removed, we decrement the replicas, and populate the podsToDelete list
    # the operator will remove pods from the list until the number of replicas is satisfied
    # when a pod is confirmed to be deleted, its name will be removed from the list below
    scaleStrategy:
      workersToDelete:
      #- raycluster-heterogeneous-worker-small-group-kxcs7
      #- raycluster-heterogeneous-worker-small-group-kvz7p
    # the following params are used to complete the ray start: ray start --block --node-ip-address= ...
    rayStartParams:
      redis-password: 'LetMeInRay'
      node-ip-address: $MY_POD_IP
    #pod template
    template:
      metadata:
        labels:
          rayCluster: raycluster-heterogeneous # will be injected if missing
          rayNodeType: worker # will be injected if missing
          groupName: small-group # will be injected if missing
        # annotations for pod
        annotations:
          key: value
      spec:
        initContainers: # to avoid worker crashing before head service is created
        # the env var $RAY_IP is set by the operator if missing, with the value of the head service name
        - name: init-myservice
          image: busybox:1.28
          command: ['sh', '-c', "until nslookup $RAY_IP.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for myservice; sleep 2; done"]   
        containers:
        - name: machine-learning # must consist of lower case alphanumeric characters or '-', and must start and end with an alphanumeric character (e.g. 'my-name',  or '123-abc'
          image: rayproject/autoscaler
          # environment variables to set in the container.Optional.
          # Refer to https://kubernetes.io/docs/tasks/inject-data-application/define-environment-variable-container/
          env:
          - name: TYPE
            value: "worker"
          - name:  RAY_DISABLE_DOCKER_CPU_WARNING
            value: "1"
          - name: CPU_REQUEST
            valueFrom:
              resourceFieldRef:
                containerName: machine-learning
                resource: requests.cpu
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          ports:
          - containerPort: 80
          # use volumeMounts.Optional.
          # Refer to https://kubernetes.io/docs/concepts/storage/volumes/
          volumeMounts:
            - mountPath: /var/log
              name: log-volume
          resources:
            limits:
              cpu: "1"
            requests:
              cpu: "200m"
        # use volumes
        # Refer to https://kubernetes.io/docs/concepts/storage/volumes/
        volumes:
          - name: log-volume
            emptyDir: {}
  - replicas: 1
    minReplicas: 0
    maxReplicas: 10
    # logical group name, for this called small-group, also can be functional
    groupName: medium-group
    # if worker pods need to be added, we can simply increment the replicas
    # if worker pods need to be removed, we decrement the replicas, and populate the podsToDelete list
    # the operator will remove pods from the list until the number of replicas is satisfied
    # when a pod is confirmed to be deleted, its name will be removed from the list below
    scaleStrategy:
      workersToDelete:
      #- raycluster-heterogeneous-worker-medium-group-7bv5h
    #  - worker-4k2ih 
    # the following params are used to complete the ray start: ray start --block --node-ip-address= ...
    rayStartParams:
      redis-password: 'LetMeInRay'
      node-ip-address: $MY_POD_IP
    #pod template
    template:
      metadata:
        labels:
          rayCluster: raycluster-heterogeneous # will be injected if missing
          rayNodeType: worker # will be injected if missing
        # annotations for pod
        annotations:
          key: value
      spec:
        initContainers:
        - name: init-myservice
          image: busybox:1.28
          command: ['sh', '-c', "until nslookup raycluster-heterogeneous-my-svc.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for myservice; sleep 2; done"]   
        containers:
        - name: machine-learning # must consist of lower case alphanumeric characters or '-', and must start and end with an alphanumeric character (e.g. 'my-name',  or '123-abc'
          image: rayproject/autoscaler
          # environment variables to set in the container.Optional.
          # Refer to https://kubernetes.io/docs/tasks/inject-data-application/define-environment-variable-container/
          env:
          - name: TYPE
            value: "worker"
          - name:  RAY_DISABLE_DOCKER_CPU_WARNING
            value: "1"
          - name: CPU_REQUEST
            valueFrom:
              resourceFieldRef:
                containerName: machine-learning
                resource: requests.cpu
          - name: CPU_LIMITS
            valueFrom:
              resourceFieldRef:
                containerName: machine-learning
                resource: limits.cpu
          - name: MEMORY_LIMITS
            valueFrom:
              resourceFieldRef:
                containerName: machine-learning
                resource: limits.memory
          - name: MEMORY_REQUESTS
            valueFrom:
              resourceFieldRef:
                containerName: machine-learning
                resource: requests.memory
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          ports:
          - containerPort: 80
          # use volumeMounts.Optional.
          # Refer to https://kubernetes.io/docs/concepts/storage/volumes/
          volumeMounts:
            - mountPath: /var/log
              name: log-volume
          resources:
            limits:
              cpu: "2"
            requests:
              cpu: "1000m"
        # use volumes
        # Refer to https://kubernetes.io/docs/concepts/storage/volumes/
        volumes:
          - name: log-volume
            emptyDir: {}
######################status#################################