apiVersion: v1
kind: Service
metadata:
  name: historyserver #TODO: to specify your service name
  labels:
    app: historyserver
spec:
  selector:
    app: historyserver
  ports:
  - protocol: TCP
    name: http
    port: 30080
    targetPort: 8080
  type: ClusterIP
